### PR TITLE
[Closes #2] Listen for Coolio

### LINKED ISSUE #2: Coolio plugin
When someone says "coolio" display a photo of Coolio!

### PR DESCRIPTION
**Pull request by doomspork**
@sobering @jamesbrink @johnTurknett — any feedback?  If you guys can round up some more links that'd be dope!

### CODE REVIEW

**Comment by doomspork** [comment]
Tested this locally and it seems to work! :tada:

**Comment by doomspork** [comment]
Before merging I'd like to add another 20 or so images.

**Comment by jcarouth** [comment]
:lollipop: Put this on your resume.

**Comment by doomspork** [comment]
Next stop :dollar: :exclamation:

**Pull request merged**
